version: '2.2'

services:
  base:
    container_name: base
    build: .
    volumes:
      - .:/var/www/base
    ports:
      - "8888:80"
    links:
      - database
  database:
    image: "mariadb:10.1.30"
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "base"
    ports:
     - "31700:3306"
