# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: bitnami/laravel
      - image: bitnami/mysql
        environment:
          - MYSQL_PASSWORD=123@123a
          - MYSQL_DATABASE=testing
          - MYSQL_ROOT_HOST=%
          - DB_HOST=127.0.0.1
          - DB_PORT=3306
          - MYSQL_USER=luonglit
          - MYSQL_ROOT_PASSWORD=123@123a

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      #- run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      #- run: sudo docker-php-ext-install zip
      #- run: sudo docker-php-ext-install gd
      #- run: sudo docker-php-ext-install xdebug
      #- run: echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so"' >> /usr/local/etc/php/php.ini
      #- run: echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/php.ini
      #- run: echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/php.ini
      #- run: echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/php.ini
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run: mysql -u root -p 123@123a -e 'show databases;'
      - run: cp .env.testing.template .env.testing
      - run: php artisan key:generate --env=testing
      - run: php artisan migrate --env=testing --force

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpcs
