version: "3"

#networks:
#  luonglit:
#    driver: bridge

services:
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=luonglit
      - MYSQL_PASSWORD=123@123a
      - MYSQL_ROOT_PASSWORD=123@123a
    restart: always
#    networks:
#      - luonglit
    tty: true
    ports:
      - "13579:3306"
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www/base
#    networks:
#      - luonglit
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254 idekey=PHPSTORM remote_enable=1
      PHP_IDE_CONFIG: serverName=docker.local
    links:
      - database
    expose:
      - "9000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www/base
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "8081:81"
      - "443:443"
    restart: always
    links:
      - php-fpm
#    networks:
#      - luonglit
    depends_on:
      - php-fpm
      - database